xhpay:
  front: windows

bot:
  token: 1444237809:AAE6DRngUsbOurVt6o4lZIidNs2KOU7RyyE
  username: fuli01_bot

file:
  outputpath: C:\\Users\\Administrator\\Documents\\
  #outputpath: /home/yangzi/software/cloudSee/
  downloadpath: C:\\Users\\Administrator\\Documents\\Group.cfg
  count: 100
  sleep: 20

server:
  #端口号
  port: 8081
  #项目名，如果不设定，默认是 /
  #context-path: /demo

spring:
  thymeleaf:
    cache: false
