xhpay:
  front: linux

bot:
  token: 1375825521:AAEU1pio1gsTxp4glYVV6x1q5VktDDck7Ys
  username: fulihao_bot

file:
  #outputpath: C:\\Users\\Administrator\\Documents\\
  outputpath: /home/yangzi/software/cloudSee/
  downloadpath: /home/yangzi/software/cloudSee/Group.cfg
  count: 2000000
  sleep: 50

server:
  #端口号
  port: 8081
  #项目名，如果不设定，默认是 /
  #context-path: /demo

mythread:
  #核心线程数量
  corepoolsize: 10
  #最大线程数量
  maxpoolsize: 128
  #队列长度
  queuecapacity: 99999

spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/telegram?useUnicode=true&characterEncoding=utf-8
    username: telegram
    password: telegram
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  map-underscore-to-camel-case: true
  type-aliases-package: com.github.xabgesagtx.example.entity  #对应实体类路径

  #设置redis服务器
redis:
  host: 127.0.0.1   #redis的服务器地址
  password:        #设置密码
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
  lettuce:
    shutdown-timeout: 30000